#TextEditor Ayarlari
#Fri May 08 21:19:32 GMT+03:00 2026
autoSavePath=C\:\\Users\\Osman Furkan Erkan\\deneme
autoSavePeriod=10
fontSize=36
highlighterColor=-6710785
padding=20
theme=Dark Theme
wordWrapEnabled=true
